export declare const PsrEntityObjectTypes: {
    readonly EntityObjectTypeUnknown: 0;
    readonly EntityObjectTypePassword: 1;
    readonly EntityObjectTypeFormular: 2;
    readonly EntityObjectTypeDocument: 3;
    readonly EntityObjectTypeRole: 4;
    readonly EntityObjectTypeUser: 5;
    readonly EntityObjectTypeGroup: 6;
    readonly EntityObjectTypeSeal: 7;
    readonly EntityObjectTypeTriggerAlert: 8;
    readonly EntityObjectTypeLogbookEntry: 9;
    readonly EntityObjectTypeContainerItem: 10;
    readonly EntityObjectTypeActiveDirectoryProfile: 11;
    readonly EntityObjectTypeSystemTask: 12;
    readonly EntityObjectTypeApplication: 13;
    readonly EntityObjectTypeMultiFactorAuthenticator: 14;
    readonly EntityObjectTypeTag: 15;
    readonly EntityObjectTypePolicy: 16;
    readonly EntityObjectTypeReportQueryConfig: 17;
    readonly EntityObjectTypeServerKey: 18;
    readonly EntityObjectTypePasswordReset: 19;
    readonly EntityObjectTypeTemplateGroup: 20;
    readonly EntityObjectTypeSealTemplate: 21;
    readonly EntityObjectTypeDiscoveredContainer: 22;
    readonly EntityObjectTypeDiscoveredContainerItem: 23;
    readonly EntityObjectTypeDataImage: 24;
    readonly EntityObjectTypeApiKey: 26;
};
export type PsrEntityObjectType = (typeof PsrEntityObjectTypes)[keyof typeof PsrEntityObjectTypes];
