export const PsrLicenseModules = {
  ModuleLicenseManagementOu: 0,
  ModuleAuditingAndReports: 1,
  ModuleNotificationSystem: 2,
  ModuleRealTimeUpdate: 3,
  ModuleAdIntegration: 4,
  ModuleAutomaticReports: 5,
  ModulePasswortReset: 6,
  ModuleApi: 7,
  ModulePki: 8,
  ModuleTwoFactorAuth: 9,
  ModuleDatabaseFirewall: 10,
  ModuleHsm: 11,
  ModuleSessionRecording: 12,
  ModuleSessionMonitoring: 13,
  ModuleOfflineAccess: 14,
  ModuleClustering: 15,
  ModuleTempRights: 16,
  ModuleTaskSystem: 17,
  ModuleSystemScanForPasswordReset: 18,
  ModuleManagingPrivilegedAccounts: 19,
  ModulePasswordLockSso: 20,
  ModuleSeal: 21,
  ModuleOfflineMode: 22,
  ModuleReplication: 23,
  ModuleDesasterWebAccess: 24,
} as const

export type PsrLicenseModule = (typeof PsrLicenseModules)[keyof typeof PsrLicenseModules]
