import type { ActiveDirectoryManager, ApplicationManager, ContainerManager, DataBindingManager, EmailVerificationManager, EncryptionManager, ExternalLinkManager, ForwardingRuleManager, GenericRightManager, LicenseManager, LogbookManager, MailingManager, OneTimePasswordManager, OptionManager, OrganisationUnitManager, PasswordManager, PolicyManager, ProgressTokenManager, PsrApi as PsrApiShape, PsrApiOptions, RealtimeEventManager, RightManager, RoleManager, SealManager, TagManager, TemplateManager, TriggerManager } from '@kmuip/pws-types';
import { RuntimeApiKeyManager } from './api-key.js';
import { RuntimeAuthenticationManager } from './authentication.js';
import type { RuntimeContext } from './runtime-context.js';
type RuntimeApiHost = PsrApiShape;
export type RuntimeBundle = {
    activeDirectoryManager: ActiveDirectoryManager;
    apiKeyManager: RuntimeApiKeyManager;
    applicationManager: ApplicationManager;
    authenticationManagerV2: RuntimeAuthenticationManager;
    containerManager: ContainerManager;
    dataBindingManager: DataBindingManager;
    emailVerificationManager: EmailVerificationManager;
    encryptionManager: EncryptionManager;
    externalLinkManager: ExternalLinkManager;
    forwardingRuleManager: ForwardingRuleManager;
    genericRightManager: GenericRightManager;
    licenseManager: LicenseManager;
    logbookManager: LogbookManager;
    mailingManager: MailingManager;
    oneTimePasswordManager: OneTimePasswordManager;
    optionManager: OptionManager;
    organisationUnitManager: OrganisationUnitManager;
    passwordManager: PasswordManager;
    policyManager: PolicyManager;
    progressToken: ProgressTokenManager;
    realtimeEventManager: RealtimeEventManager;
    rightManager: RightManager;
    roleManager: RoleManager;
    sealManager: SealManager;
    tagManager: TagManager;
    templateManager: TemplateManager;
    triggerManager: TriggerManager;
};
export declare function createRuntimeBundle(api: RuntimeApiHost, context: RuntimeContext, options?: PsrApiOptions): RuntimeBundle;
export {};
